#!/bin/bash
echo 
echo  
echo Finishing installation...
echo  
sleep 0.5s
echo  
echo ...
echo  
echo ...
echo  
echo ...
echo  
echo Running UIcache...
echo  
/usr/bin/uicache -p /Applications/DarkPapers.app
sleep 2s
echo  
echo Almost done...
sleep 2s
echo  
echo Thank you for downloading DarkPapers! Here’s the chicken pie ingredient list for you.
echo  
sleep 1s
echo  
cat << "EOF"

 ==================================
|                                  |
|            CHICKEN PIE           |
|            ~~~~~~~~~~~           |
|                                  |
|                (                 |
|                 )                |
|            __..---..__           |
|        ,-='  /  |  \  `=-.       |
|       :--..___________..--;      |
|        \.,_____________,./       |
|                                  |
|    ~~~~~~~~~~~~~~~~~~~~~~~~~~    |
|                                  |
|   A traditional chicken pie  is  | 
|   classic comfort food and this  |
|   fuss-free recipe is  one  you  |
|   will want to make over again.  |
|   It's  worth  making  your own  |
|   pastry if you can because the  |
|   ready made stuff just doesn't  |
|   match   up  to  the   buttery  |
|   loveliness    of    homemade.  |
|   _____________________________  |
|                                  |
|   INGREDIENTS:  1 medium chicken;|
|   ===========   1 peeled onion;  |
|                 6 cloves;        |
|       \/_       1 peeled carrot; |
|      _/         2 bay leaves;    |
|     (,;)        1 chicken stock  |
|     (,.)        cube;            |
|     (,/         6-8 peppercorns; |
|     |/                           |
|                                  |
|                                  |
|   FOR THE PASTRY:  450g/1lb plain|
|   ===============  flour;        |
|                    1/2 tsp salt; |
|         .          120g/4oz vege-|
|       .:.;.        -table shorte-|
|      :;,::,;       -ning, cold;  |
|     =========      1 beaten egg; |
|                                  |
|                                  |
|   FOR THE SAUCE:  250ml/9fl oz w-|
|   ==============  -hole milk;    |
|                   55g/2oz butter;|
|                   55g/2oz  plain |
|                   flour;         |
|                                  |
 ==================================

EOF

echo ===========================
echo     "Special Thanks To:"
echo ===========================
echo   
echo skittyblock, for the guide on how to manually load the wallpapers;
echo  
echo MichaelMKenny, for the awesome proof of concept app;
echo  
echo You for reading my chicken pie ingredients list! ... and for downloading this tweak too, obviously.
echo  
echo ===========================
echo 
echo  
echo Ready to Respring...
sleep 1s
killall SpringBoard
