#!/bin/bash
cd /System/Library/Audio/UISounds/SiriBackup
cp ./jbl_begin.caf /System/Library/Audio/UISounds/jbl_begin.caf
cd /System/Library/Audio/UISounds/SiriBackup
cp ./jbl_confirm.caf /System/Library/Audio/UISounds/jbl_confirm.caf
sleep 3
echo “Reboot your device for the changes to take place! A respring won’t make it work.”


exit 0

